// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgPlffYCDeiT9y9-wksDgfn6EmxGoW5ps',
    appId: '1:523639579232:web:f8690683b920d2444ad905',
    messagingSenderId: '523639579232',
    projectId: 'flutter-crud-f942a',
    authDomain: 'flutter-crud-f942a.firebaseapp.com',
    storageBucket: 'flutter-crud-f942a.appspot.com',
    measurementId: 'G-PXSEDJZX24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCO4giTr5n_3lxLT-WAaw1SD89YaEElDA',
    appId: '1:523639579232:android:0f0c9b40a0eba0a04ad905',
    messagingSenderId: '523639579232',
    projectId: 'flutter-crud-f942a',
    storageBucket: 'flutter-crud-f942a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbo5wTIBJRLH01XBjQ0_R7zAQ8DtoMo9Y',
    appId: '1:523639579232:ios:d130c245f519f7704ad905',
    messagingSenderId: '523639579232',
    projectId: 'flutter-crud-f942a',
    storageBucket: 'flutter-crud-f942a.appspot.com',
    iosClientId: '523639579232-n82l479nofeu3rqk6603e6q8nv8u76pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbo5wTIBJRLH01XBjQ0_R7zAQ8DtoMo9Y',
    appId: '1:523639579232:ios:d130c245f519f7704ad905',
    messagingSenderId: '523639579232',
    projectId: 'flutter-crud-f942a',
    storageBucket: 'flutter-crud-f942a.appspot.com',
    iosClientId: '523639579232-n82l479nofeu3rqk6603e6q8nv8u76pk.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudFirebase',
  );
}
